CreateQuiz/urls.py
from django.urls import path
from .views import AvailableQuizzes, CreateQuiz, CreateQuestion, QuizCreated

urlpatterns = [
    path('availablequizzes/', AvailableQuizzes, name='availablequizzes'),
    path('createquiz/', CreateQuiz),
    path('createquestions/<int:id>/<int:no>', CreateQuestion),
    path('quizcreated/', QuizCreated, name='QuizCreated')
]

OnlineQuiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from Students import urls as StudentUrls
from School import urls as SchoolUrls
from CreateQuiz import urls as CQUrls
from Results import urls as ResultsUrls
from TakeQuiz import urls as TakeQuizUrls
from Accounts import urls as AccountUrls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(AccountUrls)),
    path('', include(StudentUrls)),
    path('', include(SchoolUrls)),
    path('', include(CQUrls)),
    path('',include(ResultsUrls)),
    path('',include(TakeQuizUrls)),
]

School/urls.py
from django.contrib.auth import logout
from django.urls import path
from .views import StaffLogin, StaffRegister, Logout

urlpatterns = [
    path('stafflogin/', StaffLogin, name='stafflogin'),
    path('staffregister/', StaffRegister, name='staffregister'),
    path('logout/', Logout, name='logout')  
]

CreateQuiz/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.lookups import Transform

class Quiz(models.Model):
    QuizId = models.AutoField(primary_key=True, editable=False)
    QuizName = models.CharField(max_length=50)
    QuizCreator = models.ForeignKey(User, on_delete=models.CASCADE)
    DateOfCreation = models.DateTimeField(auto_now_add=True)
    DueDate = models.DateTimeField()

    def __str__(self):
        return self.QuizName

class Questions(models.Model):
    
    QuizName = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    Question = models.TextField()

    OptionA = models.TextField()
    OptionB = models.TextField()
    OptionC = models.TextField()
    OptionD = models.TextField()

    CorrectChoise1 = models.CharField(max_length=1)
    CorrectChoise2 = models.CharField(max_length=1,null=True, blank=True)
    CorrectChoise3 = models.CharField(max_length=1,null=True, blank=True)

    def __str__(self):
        return self.Question

CreateQuiz/forms.py
from django.forms import ModelForm, fields
from django.forms import Form
from .models import Quiz, Questions

class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = '__all__'

CreateQuiz/views.py
from django.shortcuts import redirect, render
from .models import Quiz, Questions
from django.contrib.auth.decorators import login_required

@login_required(login_url='/stafflogin')
def AvailableQuizzes(request):

    quizzes = list(Quiz.objects.all())
    
    context = {
        'quizzes' : quizzes
    }

    return render(request, 'availablequizzes.html', context)

@login_required(login_url='/stafflogin')
def CreateQuiz(request):

    quiz = Quiz()

    if request.method == 'POST':
        
        quizname = request.POST.get('QuizName')
        quizcreator = request.user
        duedate = request.POST.get('DueDate')

        quiz = Quiz(QuizName=quizname, QuizCreator=quizcreator, DueDate = duedate)

        quiz.save()

        return redirect(f'/createquestions/{quiz.QuizId}/0')

    context = {
        'staff' : request.user,
    }
    
    return render(request, 'createquiz.html', context)

@login_required(login_url='/stafflogin')
def CreateQuestion(request, id, no):
    
    
    if no < 10:
        quiz = Quiz.objects.get(QuizId=id)
        if request.method == 'POST':
            no += 1
            
            question = request.POST.get('Question')
            
            optionA = request.POST.get('OptionA')
            optionB = request.POST.get('OptionB')
            optionC = request.POST.get('OptionC')
            optionD = request.POST.get('OptionD')

            correctoption1 = request.POST.get('CorrectChoise1')
            correctoption2 = request.POST.get('CorrectChoise2')
            correctoption3 = request.POST.get('CorrectChoise3')

            question = Questions(
                QuizName=quiz, 
                Question=question, 
                OptionA=optionA, 
                OptionB=optionB, 
                OptionC=optionC, 
                OptionD=optionD,
                CorrectChoise1=correctoption1,
                CorrectChoise2=correctoption2,
                CorrectChoise3=correctoption3, 
                )
            question.save()

            return redirect(f'/createquestions/{id}/{no}')
        
        context = {
            
            'quizname':quiz.QuizName
        }
        return render(request, 'createquestion.html', context)

    else:
        return redirect('QuizCreated')

@login_required(login_url='/stafflogin')
def QuizCreated(request):
    return render(request, 'quizcreated.html')

CreateQuiz/templates/availablequizzes.html
{% extends 'home.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/tablestyle.css' %}">
{% endblock %}

{% block nav %}
    {% include 'nav.html'%}
{% endblock %}

{% block content %}




    <div class="create-quiz">
        <a href="/createquiz">
            <h2>
                Create a New Quiz
            </h2>
        </a>
    </div>
    

    <div class="table-container">

        <table>
            <tr>
                <th>Quiz ID</th>
                <th>Quiz name</th>
                <th>Quiz Creator</th>
                <th>Date Of Creation</th>
                <th>DueDate</th>
            </tr>
            

        {% for quiz in quizzes %}
            <tr>
                <td>
                    {{ quiz.QuizId }}
                </td>
                <td>
                    <a href="{{ quiz.QuizId }}/">
                        {{ quiz.QuizName }}
                    </a>
                </td>
                <td>
                    {{ quiz.QuizCreator }}
                </td>
                <td>
                    {{ quiz.DateOfCreation }}
                </td>
                <td>
                    {{ quiz.DueDate }}
                </td>
            </tr>
        {% endfor %}

        </table>

    </div>



{% endblock %}

CreateQuiz/templates/createquestion.html
{% extends 'home.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/questions.css' %}">
{% endblock %}

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

{% block content %}

<div class="main-content">

    <div>
        <h3>Quiz Name: {{quizname}}</h3>
    </div>

    <form action="" method="post" class="form-box">
        {% csrf_token %}
        <div class='box'>
            <label for="Question">Question</label><br>
            <input type="text" name = "Question" id = "id_Question" required>
        </div>
        <div class='box'>
            <label for="OptionA">OptionA</label><br>
            <input type="text" name = "OptionA" id = "id_OptionA" required>
        </div>
        <div class='box'>
            <label for="OptionB">OptionB</label><br>
            <input type="text" name = "OptionB" id = "id_OptionB" required>
        </div>
        <div class='box'>
            <label for="OptionC">OptionC</label><br>
            <input type="text" name = "OptionC" id = "id_OptionC" required>
        </div>
        <div class='box'>
            <label for="OptionD">OptionD</label><br>
            <input type="text" name = "OptionD" id = "id_OptionD" required>
        </div>
        <div class='box'>
            <label for="id_CorrectChoise1">CorrectChoise1</label><br>
            <select name="CorrectChoise1" id="id_CorrectChoise1" required>
                <option value="" selected>-----</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>
        </div>
        <div class='box'>
            <label for="CorrectChoise2">CorrectChoise2</label><br>
            <select name="CorrectChoise2" id="id_CorrectChoise2">
                <option value="" selected>-----</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>
        </div>
        <div class='box'>
            <label for="CorrectChoise3">CorrectChoise3</label><br>
            <select name="CorrectChoise3" id="id_CorrectChoise3">
                <option value="" selected>-----</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>
        </div>
        <div class='box'>
            <input type="submit" value="Add Question">
        </div>
        
    </form>
</div>

{% endblock %}

CreateQuiz/templates/createquiz.html
{% extends 'home.html' %}

{% block style%}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quizdetails.css'%}">
    
{% endblock %}

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

{% block content %}

<div class="quiz-details full-size">

    <div class="fit-box">

        <h3>
            Enter Quiz Details
        </h3>
    
        <form action="" method="post" class="quiz-details form-size">
            {% csrf_token %}
            <div class="box">
                <label for="id_QuizName">Quiz Name</label>
                <input type="text" name="QuizName" id="id_QuizName" required>
            </div>
            <div class="box">
                <label for="id_QuizCreator">Quiz Creator</label>
                <input type="text" name="QuizCreator" id="id_QuizCreator" required value={{ staff }} readonly>
            </div>
            <div class="box">
                <label for="id_DueDate">DueDate</label>
                <input type="text" name="DueDate" id="id_DueDate" placeholder = 'yyyy-mm-dd'required>
        
            </div>
            <div class="box">
                <input type="submit" value="Create quiz">
            </div>
        </form>
    
    </div>
    
</div>

{% endblock %}

CreateQuiz/templates/quizcreated.html
{% extends 'home.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quizcreated.css' %}">
    
{% endblock %}

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

{% block content %}
<div class="main-content">

    <div class="box">
        <h1>Quiz Created</h1>
        <a href="/availablequizzes">back to main page</a>
    </div>

</div>
{% endblock %}